In [3]:
!pip install torch torchvision torchaudio

  Using cached torch-2.11.0-cp313-cp313-win_amd64.whl.metadata (29 kB)
  Using cached torchvision-0.26.0-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Using cached torch-2.11.0-cp313-cp313-win_amd64.whl (114.6 MB)
Using cached torchvision-0.26.0-cp313-cp313-win_amd64.whl (4.3 MB)

   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- ----------------

In [4]:
import torch
print(torch.__version__)

2.11.0+cpu


In [5]:
import torch 
import torch.nn as nn


In [6]:
#inputs
inputs=torch.tensor([1.0,2.0,3.0])

In [15]:
torch.manual_seed(42)
neuron=nn.Linear(in_features=3,out_features=1)
output=neuron(inputs)

In [16]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [17]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [18]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [19]:
#verify formula
neuron.weight@inputs+neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)